# Generated by Django 5.2.3 on 2025-06-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='reting',
            new_name='rating',
        ),
    ]
